### ISSUE TITLE
Using custom vhost

### ISSUE THREAD

**Issue by brendan-rius** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#193]
I followed your guide and it works great. Here is my configuration:

```yml
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
```

The problem is that I want to keep my per virtual-host configuration, so I want to bind the vhost to a host volume like so:

```yml
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d # ======== HERE <<<<<< ==== 
      - /usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
```

When I do that, the validation fails (it cannot find the well known file). Here is an extract from the Docker logs:

```
nginx                                | MYWEBSITE IP - - [07/Apr/2017:18:45:28 +0000] "GET /.well-known/acme-challenge/XXX HTTP/1.1" 404 155 "-" "python-requests/2.8.1"
letsencrypt-nginx-proxy-companion    | 2017-04-07 18:45:28,045:WARNING:simp_le:1303: api.welovedaze.com was not successfully self-verified. CA is likely to fail as well!
letsencrypt-nginx-proxy-companion    | 2017-04-07 18:45:28,286:INFO:simp_le:1313: Generating new certificate private key
nginx                                | MYWEBSITE IP - - [07/Apr/2017:18:45:28 +0000] "GET /.well-known/acme-challenge/XXX HTTP/1.1" 404 155 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
letsencrypt-nginx-proxy-companion    | 2017-04-07 18:45:29,115:ERROR:simp_le:1271: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Is there a warning log entry about unsuccessful self-verification? Are all your domains accessible from the internet? Failing authorizations: https://acme-staging.api.letsencrypt.org/acme/authz/XXX
letsencrypt-nginx-proxy-companion    | Challenge validation has failed, see error log.
```

How can I keep my per vhost config, while still using your project?

Thanks!

**EDIT:**

If I manually add 

```
location /.well-known/acme-challenge/ {
    allow all;
    root /usr/share/nginx/html;
    try_files $uri =404;
    break;
}
```

in my vhost config, it gets validated (because the well-known file is found), but then I have this weird error message:

```
nginx-gen                            | 2017/04/07 18:55:45 Generated '/etc/nginx/conf.d/default.conf' from 9 containers
nginx-gen                            | 2017/04/07 18:55:45 Sending container 'nginx' signal '1'
nginx                                | 2017/04/07 18:55:45 [emerg] 1#1: duplicate location "/.well-known/acme-challenge/" in /etc/nginx/vhost.d/MYWEBSITE:9
```

it looks like it might be trying to add the block after I added it :/
