### ISSUE TITLE
Don't always create a new certificate on startup

### ISSUE THREAD

**Issue by jsaalfeld** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#374]
Hi there,

I got the Issue [in a project of mine](https://github.com/OpenSlides/openslides-docker), that the companion creates a new certificate on every ```docker-compose up``` even though valid certificates are already in place from a startup before. Is there a flag or a way to tell the companion, to first look if in the certs folder are already valid certificates for the ```VIRTUAL_HOST```?

**Comment by buchdag** [comment]
Hi.

What version of the container are you using ?

Do you have any log output from the container ?

**Comment by jsaalfeld** [comment]
For development purposes i regulary deleted my images, so it is the latest version available thorugh the docker repository.

What kind of logs do you need? Do you look for something special? From what containers?

**Comment by buchdag** [comment]
Okay, before we start digging into logs, how did you arrive at the conclusion that the container creates new certificates on every `docker-compose up` ?

**Comment by jsaalfeld** [comment]
In 2 ways:
1. The logs running through always stated something about certificate creation and i saw in the nginx logs, that the ```.well-known``` was reached out to
2. After a couple of ```docker-compose down``` and ```docker-compose up``` on a system, the companion stated, that we reached the maximum of certificate requests for that domain in that week

**Comment by jsaalfeld** [comment]
As you can see from the linked repo in the start of the thread, there are no additional scripts to prune volumes etc.

The interesting thing is: When i let the companion create the certificates in the first start and then scale the companion down to 0 in the next start, nginx will successfully recognize the certificates. So no: I don't think there is something fishy with the volumes.

**Comment by buchdag** [comment]
I'll give a shot at your repo as soon as possible but I didn't see anything out of the ordinary either.

**Comment by jwulf** [comment]
> For development purposes i regulary deleted my images, so it is the latest version available thorugh the docker repository.


If you also delete your volumes, there will be no cached certificate, so it will request a new one.

**Comment by jwulf** [comment]
I actually ran into this issue, without deleting volumes.

To get around it, I created two separate docker-compose files: one for the nginx/lets-encrypt combo, and another one for my webapp. I set my CD system to bring the webapp up and down, and not touch the proxy docker instance.

That got around it.

**Comment by belzebalex** [comment]
Hello,
I'm having the same problem, which is kind of problematic as certificate creations create a few minutes of downtime.
Is there any fix ?

**Comment by buchdag** [comment]
> Is there any fix ?

No clear and reproducible issue has been identified, so there is unfortunately nothing to fix at this point.

Under normal operation the container does not recreate existing certificate on restart and I haven't observed this behaviour on any of my own servers.

If your compose file don't use external volumes, the volume creation / deletion is handled by docker-compose itself and you might be deleting or recreating your volumes without realising it. Please check `docker-compose` doc, watch your Docker volumes and the `docker-compose` command output.

Is `docker-compose down` deleting your volumes ?
Is `docker-compose up` creating new volumes ?

**Comment by belzebalex** [comment]
> > Is there any fix ?
> 
> No clear and reproducible issue has been identified, so there is unfortunately nothing to fix at this point.
> 
> Under normal operation the container does not recreate existing certificate on restart and I haven't observed this behaviour on any of my own servers.
> 
> If your compose file don't use external volumes, the volume creation / deletion is handled by docker-compose itself and you might be deleting or recreating your volumes without realising it. Please check `docker-compose` doc, watch your Docker volumes and the `docker-compose` command output.
> 
> Is `docker-compose down` deleting your volumes ?
> Is `docker-compose up` creating new volumes ?

I guess docker-compose isn't deleting / creating volumes. Is there any way to be sure ?
```
version: 2.1
services:
    nginx-proxy:
        restart: always
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /srv/docker/nginx/certs:/etc/nginx/certs:ro
            - /etc/nginx/vhost.d
            - /usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./http_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro

    nginx-proxy-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        volumes:
            - /srv/docker/nginx/certs:/etc/nginx/certs:rw
            - /var/run/docker.sock:/var/run/docker.sock
        volumes_from:
            - nginx-proxy
```
Is there anything wrong with my docker-compose configuration ?

Nevertheless, each time I'm restarting my server (docker-compose down, then docker-compose up), openssl uses 100% of the CPU during ~2 minutes, locking my whole server. 

Thanks in advance for any help.

Alex

**Comment by buchdag** [comment]
The heavy CPU consuming openssl process at start is probably the 2048 bits DH parameters generation, but like the rest it should only happen once. It's also heavily `nice`'d and should not lock anything beside extremely small single core servers (the only thing I run that have issue with it is a Google Cloud f1-micro instance, and even that become slow but not locked), what hardware or VM are you running this on ?

Your container appears to be acting exactly as if its `/etc/nginx/certs` folder was wipped on each restart.

What happen to the files inside your `/srv/docker/nginx/certs` folder after a `docker-compose down` ?

Could you try using a Docker named volume for `/etc/nginx/certs` instead of a bind mount ?

```yaml
version: 2.1
services:
    nginx-proxy:
        restart: always
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - certs:/etc/nginx/certs:ro
            - /etc/nginx/vhost.d
            - /usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./http_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro

    nginx-proxy-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        volumes:
            - certs:/etc/nginx/certs:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro
        volumes_from:
            - nginx-proxy

volumes:
  certs:
```

**Comment by belzebalex** [comment]
Hello,

Sorry if I was misunderstood. It doesn't lock the system completely, but the website is inaccessible (which is normal).

After a docker-compose down, the files stay the same. 

I'll try with the bind mount, I'll keep you informed.

**Comment by dm17** [comment]
@jwulf Can I see an example of how you did that? Would be nice to leave the existing docker-compose.yaml alone and have a separate one that acts on it for the nginx/letsencrypt functionality.

**Comment by jwulf** [comment]
Here you go: https://github.com/jwulf/letsencrypt-nginx-sidecar

**Comment by buchdag** [comment]
This issue has been inactive for a while, closing.

**Comment by nekym** [comment]
I'm having the same problem with recreating certificates. 
I understood it when I got the max limit message from the container logs and cannot access the website because the container removed my previous certificates. 

System: win 10 + WSL2
I launch docker from windows of course.

I took the docker compose file from the nextcloud examples and made small changes for changing the path with volumes data.
Also I have the problem that somebody creates an unnamed docker volume every time. 

```

version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - E:\db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passFromDB
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - E:\nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    volumes:
      - E:\nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=myhost.example
      - LETSENCRYPT_HOST=myhost.example
      - LETSENCRYPT_EMAIL=email@example.com
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - E:\nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
```

**Comment by buchdag** [comment]
@nekym please take a look at the information on the beginning of the README about the new volume required by the version 2 of the container.

**Comment by nekym** [comment]
@buchdag I'm sorry for the stupid question, but if I correctly understood the readme header I have to add `- acme:/etc/acme.sh` in my 'volumes' block, right?
I tried to read the topic which is noted in the beginning, but it is too hard for understanding for a person who does not work with certificates and security :-).

**Comment by jwulf** [comment]
> @buchdag I'm sorry for the stupid question, but if I correctly understood the readme header I have to add `- acme:/etc/acme.sh` in my 'volumes' block, right?
> I tried to read the topic which is noted in the beginning, but it is too hard for understanding for a person who does not work with certificates and security :-).

It is this in the nginx-proxy:  `--volume certs:/etc/nginx/certs \`

and this in the nginx-proxy-companion: `--volumes-from nginx-proxy \`

**Comment by buchdag** [comment]
@nekym sorry I completely forgot to get back to you, yes you got that right, I'll post an exemple config updated from yours tomorrow.

**Comment by buchdag** [comment]
@nekym so based on your existing config:

```yaml
version: '3'

services:
[...]
  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh # Mount the acme volume to the companion
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  certs:
  vhost.d:
  html:
  acme: # Add the acme volume to your compose file
[...]
```
