### ISSUE TITLE
Using multiple web app

### ISSUE THREAD

**Issue by stephane-r** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#418]
Hi,

I've try to use this container for multiple web app. For my first subdomaine, it work very nice, but for my all subdomaine, browser return `NET::ERR_CERT_COMMON_NAME_INVALID`.

If i see the `Subject` (on chrome), i see my first subdomaine (working) : 

![nginx](https://user-images.githubusercontent.com/4712791/43267590-a6599b14-90ee-11e8-9edf-0c15c70c64f0.jpg)

When i check my `certs` folder, i see all subdomaine with `.chain.pem` and `.crt` files.

Is there something I did wrong ? ^^

Thank you !

**Comment by buchdag** [comment]
Can you provide the config (compose file or CLI commands) you are using to setup your nginx-proxy and letsencrypt containers, and the logs from the containers ?

**Comment by stephane-r** [comment]
Hi @buchdag 

My **letsencrypt-nginx-proxy** container : 

```
version: '2'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:

networks:
  default:
    external:
      name: nginx-proxy
```

Portainer docker-compose file (subdomaine working) : 

```
version: '3'

services:
    portainer:
        image: portainer/portainer
        container_name: portainer
        restart: always
        environment:
            - VIRTUAL_HOST=portainer.${SITE_URL}
            - VIRTUAL_PORT=9000
            - LETSENCRYPT_HOST=portainer.${SITE_URL}
            - LETSENCRYPT_EMAIL=${MAILER_DEFAUT_SENDER_ADDRESS}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data:/data
        ports:
            - '9000:9000'

networks:
    default:
        external:
            name: nginx-proxy
```

An other docker-compose file not working (`NET::ERR_CERT_COMMON_NAME_INVALID` error) : 

```
version: "2"

services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
      - VIRTUAL_HOST=sonarr.${SITE_URL}
      - VIRTUAL_PORT=8989
      - LETSENCRYPT_HOST=sonarr.${SITE_URL}
      - LETSENCRYPT_EMAIL=${MAILER_DEFAUT_SENDER_ADDRESS}
    volumes:
      - ${MOUNT_POINT}/sonarr/config:/config
      - ${MEDIA_PATH}:/tv
      - ${DOWNLOAD_PATH}:/downloads

networks:
    default:
        external:
            name: nginx-proxy
```

I run all docker-compose file with `docker-compose up -d` command. All app is separate : it's not only one **docker-compose.yml** file.

Thank you for your help !

**Comment by stephane-r** [comment]
@buchdag Do you think i need use `letsencrypt-nginx-proxy-companion` container directly in the webapp ?

**Comment by SFoskett** [comment]
I am seeing this same issue with multiple hosts. test1.example.com works fine but test2.example.com never gets a cert so gives Error 500 when using https. Connecting with http://test2.example.com works fine but that pretty much misses the point.

**Comment by buchdag** [comment]
Have you both followed the troubleshooting steps for failed auth described in the project wiki?

**Comment by stephane-r** [comment]
Hi guys !

I've "resolve" my problem with this `docker-compose.yml` : 

```
version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:                     
      - ./current/public:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - ./vhost:/etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./vhost:/etc/nginx/vhost.d
      - ./current/public:/usr/share/nginx/html

volumes:
  vhost:
networks:
  default:
    external:
      name: nginx-proxy
```

I say "resolve" because if i add new `supersubdomain.my-site.com`, i've only the folder create in `certs`, not pem files.
