### ISSUE TITLE
No certs for grafana

### ISSUE THREAD

**Issue by vonAlenberg** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#618]
I know, seems to be trivial, but I don't get it to work, so maybe someone more clever than me spots the mistake ;)

docker-compose for reverse proxy and le companion
```yaml
version: '3'

services:
  proxy:
    build: ./reverse_proxy
    container_name: proxy
    restart: always
    ports:
      - 80:80
      - 443:443
      - 25:25
      - 465:465
      - 587:587
      - 143:143
      - 993:993
      - 110:110
      - 905:905
      - 4190:4190
    volumes:
      - ${DOCKERDIR}/reverse_proxy/certs:/etc/nginx/certs:ro
      - ${DOCKERDIR}/reverse_proxy/vhost.d:/etc/nginx/vhost.d
      - ${DOCKERDIR}/reverse_proxy/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - PUID=33
      - PGID=33
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - proxy-tier

  le:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: le
    depends_on:
      - proxy
    volumes:
      - ${DOCKERDIR}/reverse_proxy/certs:/etc/nginx/certs:rw
      - ${DOCKERDIR}/reverse_proxy/vhost.d:/etc/nginx/vhost.d
      - ${DOCKERDIR}/reverse_proxy/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PUID=33
      - PGID=33
      - DEFAULT_EMAIL=j.s@geruja.de
      - NGINX_PROXY_CONTAINER=proxy
      - DEBUG=true
    networks:
      - proxy-tier

networks:
  proxy-tier:
    driver: bridge

```

docker compose for grafana
```yaml
version: '3'

services:
  mon_prometheus:
    image: prom/prometheus:latest
    container_name: mon_prometheus
    restart: unless-stopped
    volumes:
      - ${DOCKERDIR}/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - mon_node-exporter
      - mon_cadvisor
    networks:
      - internal

  mon_node-exporter:
    image: prom/node-exporter:latest
    container_name: mon_node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    networks:
      - internal

  mon_cadvisor:
    image: google/cadvisor:latest
    container_name: mon_cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - internal

  mon_grafana:
    image: grafana/grafana:latest
    container_name: mon_grafana
    restart: unless-stopped
    volumes:
      - /mnt/data-storage/grafana:/var/lib/grafana
#      - ${DOCKERDIR}/reverse_proxy/certs/monitoring.i-amboss.com:/etc/letsencrypt/certs:ro
    user: "0" # USER ID des Docker Users anpassen
    depends_on:
      - mon_prometheus
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_PROTOCOL=http
      - VIRTUAL_HOST=monitoring.i-amboss.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=monitoring.i-amboss.com
    networks:
      - internal
      - docker_proxy-tier

networks:
  internal: 

  docker_proxy-tier:
    external: true

```

And the DNS entries from Cloudflare:
```
A              domain.com     1.2.3.4
CNAME     monitoring       domain.com
```

As I read the troubleshooting and added `DEBUG` to the ENV, this the error response
```
Creating/renewal monitoring.i-amboss.com certificates... (monitoring.i-amboss.com)
2020-02-10 21:04:25,258:DEBUG:simp_le:1522: ('-f', 'account_key.json', '-f', 'account_reg.json', '-f', 'key.pem', '-f', 'chain.pem', '-f', 'fullchain.pem', '-f', 'cert.pem', '--email', 'j.s@geruja.de', '-v', '--valid_min', '2592000', '-d', 'monitoring.i-amboss.com', '--cert_key_size=4096', '--server=https://acme-v02.api.letsencrypt.org/directory', '--default_root', '/usr/share/nginx/html/') parsed as Namespace(account_key_public_exponent=65537, account_key_size=4096, ca_bundle=None, cert_key_size=4096, default_root='/usr/share/nginx/html/', email='j.s@geruja.de', help=False, integration_test=False, ioplugins=['account_key.json', 'account_reg.json', 'key.pem', 'chain.pem', 'fullchain.pem', 'cert.pem'], reuse_key=False, revoke=False, server='https://acme-v02.api.letsencrypt.org/directory', test=False, user_agent='simp_le/0.16.0', valid_min=2592000, verbose=True, version=False, vhosts=[Vhost(name='monitoring.i-amboss.com', root=None)])
2020-02-10 21:04:25,259:DEBUG:simp_le:372: Loading account_key.json
2020-02-10 21:04:25,261:DEBUG:simp_le:372: Loading account_reg.json
2020-02-10 21:04:25,261:DEBUG:simp_le:372: Loading key.pem
2020-02-10 21:04:25,261:DEBUG:simp_le:372: Loading chain.pem
2020-02-10 21:04:25,261:DEBUG:simp_le:372: Loading fullchain.pem
2020-02-10 21:04:25,261:DEBUG:simp_le:372: Loading cert.pem
2020-02-10 21:04:25,261:DEBUG:simp_le:1405: Computed roots: {'monitoring.i-amboss.com': '/usr/share/nginx/html/'}
2020-02-10 21:04:25,261:DEBUG:acme.client:1104: Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2020-02-10 21:04:25,263:DEBUG:urllib3.connectionpool:959: Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2020-02-10 21:04:25,848:DEBUG:urllib3.connectionpool:437: https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2020-02-10 21:04:25,849:DEBUG:acme.client:1145: Received response:
HTTP 200
Server: nginx
Date: Mon, 10 Feb 2020 21:04:25 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "4pDkwSYMLMk": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2020-02-10 21:04:25,849:INFO:simp_le:1414: Generating new certificate private key
2020-02-10 21:04:26,968:DEBUG:acme.client:1177: Requesting fresh nonce
2020-02-10 21:04:26,968:DEBUG:acme.client:1104: Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2020-02-10 21:04:27,112:DEBUG:urllib3.connectionpool:437: https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2020-02-10 21:04:27,113:DEBUG:acme.client:1145: Received response:
HTTP 200
Server: nginx
Date: Mon, 10 Feb 2020 21:04:27 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0001qjCkU7nujjNm4Ji9rs0n6yADAF7NoNKmFZknSIOQLCc
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2020-02-10 21:04:27,113:DEBUG:acme.client:1170: Storing nonce: 0001qjCkU7nujjNm4Ji9rs0n6yADAF7NoNKmFZknSIOQLCc
2020-02-10 21:04:27,114:DEBUG:acme.client:1012: JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "monitoring.i-amboss.com"\n    }\n  ]\n}'
2020-02-10 21:04:27,123:DEBUG:acme.client:1102: Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvNzQ4MzAyODgiLCAibm9uY2UiOiAiMDAwMXFqQ2tVN251ampObTRKaTlyczBuNnlBREFGN05vTkttRlprblNJT1FMQ2MiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "h4SlVHjfBl7jdjvRMAym_-fm8aiTNIAeJRh_ffPUYAcXbLnp4GMS4iFbQfrpJnyiVXS24Kxi3iSFvbANlZaVBTjZAsO4uSjeQpMqlfb_TCKHJlX6d3x_-yPvDCibKaP6w_4xTi_lcGpa09NDYRvbXYJCvHqVFQMddUtrUT7TBgI0_X4PGj1tPH5oM2QGIkfaCqkatrt8QYJZ1exFb34JeGqyrhMEPIG6qgP-kMS6UhoABy8UTPXsFvlwMupspAKqZ0dpQGcOsoB8D5u3CuSAc1CyhiigDPKgLwgUMaAUMq9UE7qDt1VxHqAL5kx_KGfzgTZgF1_aly5yynsI2DLcyjjFWILR_cVmq6HTc-Z3G8DE43Wtbrqn3ZacqGq_rspm4E4kZC_uaFUoFVcvHaORTCEssKrDt9Yhm4Pkd5qZiP-jsIEJH9oIbN0IBvLiBHHN-q93_6m5jIAaT3allPsprA05bC4qtUbZQH-3DFxUf92kNK6G0HG4JBLnH5QXAc5qRxFQfymJ_s-FC8vIorOyq6IEozrJsfc93zjnVMynRo65fI3dhAA8PxUzGZpRgSjC-nvUQz7oz4pyWgdmggPBJJdJxJ-BZcVy4GsqHhFmV78C5vU2fIE2MWz0Y2J6KH0bSoO3t5K4B5E0SiKDaEe1n2yWA7LHlCk9WFAwDxxdK0Y",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogIm1vbml0b3JpbmcuaS1hbWJvc3MuY29tIgogICAgfQogIF0KfQ"
}
2020-02-10 21:04:27,308:DEBUG:urllib3.connectionpool:437: https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 353
2020-02-10 21:04:27,309:DEBUG:acme.client:1145: Received response:
HTTP 201
Server: nginx
Date: Mon, 10 Feb 2020 21:04:27 GMT
Content-Type: application/json
Content-Length: 353
Connection: keep-alive
Boulder-Requester: 74830288
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/74830288/2293200636
Replay-Nonce: 0002LsWCUNT8fxCt4EMMTbmA57WB35DcwgBL5Vx2n19i4rQ
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2020-02-17T21:04:27.219181707Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "monitoring.i-amboss.com"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/2748110792"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/74830288/2293200636"
}
2020-02-10 21:04:27,309:DEBUG:acme.client:1170: Storing nonce: 0002LsWCUNT8fxCt4EMMTbmA57WB35DcwgBL5Vx2n19i4rQ
2020-02-10 21:04:27,312:DEBUG:acme.client:1012: JWS payload:
b''
2020-02-10 21:04:27,322:DEBUG:acme.client:1102: Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/2748110792:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvNzQ4MzAyODgiLCAibm9uY2UiOiAiMDAwMkxzV0NVTlQ4ZnhDdDRFTU1UYm1BNTdXQjM1RGN3Z0JMNVZ4Mm4xOWk0clEiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzI3NDgxMTA3OTIifQ",
  "signature": "bU-zb0y45pM9Wit2idgLfvq2CjxC5iA7732dUPXBPhcRjulYLupxzF19ts6qF8XQIhjp5_mlUnmJSGW9i6UqS-YChU1rkv0PuOi-kmIxB72Kh65DosMjRmfr2pxq__OOUPIZbRujP1TzQz-uPbRgzWt5546qL_zZl5a31S1qsEjDvJtwN9LXmw5HLLOkSaAaERxJHY1cDEkgJH5v4yI10Cr_SOFEDrkrjUoYifxVwiL-zuBQgmLj7z9mSfrU7oto36uzTTrSHl7NOs8_EWxh3HJzJjRogIqx6zC7yWvgj_p1zgiSE5oSeyo4973r0pmc_wd1yG_OSHq7s4_zpVoXvAT2nC3mNRe7vudJ0EO6b37yhYPAxik1GjDRMFpRetmRa4c2NWCYhCBfJnjbVUu7cpjqkJKViAYXfa6B_q5PjbxPEPL_iJXHJcoPGjCSMRELsDeOgYP6nPLYmpE0qlaX3cr0cjRl9tXdZBaVVGMKfOjW1A0XS2cxCFOQEmOjrk2IDajvBAm9dh1Z0X_yHGX3s-ZBeDOCEbpYRCa5Mq_cuMJXXa81KCEEjoD3RcTgbVVR_qB0sFVncLePKlJ-jWVaUVubhIqUIfojqNBSjEnITHNUhIfMwVraOxtOurpZW971u4Shb5E6aABY6Yc1mFMOZLUVfNMLWrNCux4_3JdFJqE",
  "payload": ""
}
2020-02-10 21:04:27,479:DEBUG:urllib3.connectionpool:437: https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/2748110792 HTTP/1.1" 200 801
2020-02-10 21:04:27,480:DEBUG:acme.client:1145: Received response:
HTTP 200
Server: nginx
Date: Mon, 10 Feb 2020 21:04:27 GMT
Content-Type: application/json
Content-Length: 801
Connection: keep-alive
Boulder-Requester: 74830288
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0002A1ZWYw5SSWty03afvlLEDfWvcN6QfziDEROm1dNVyBI
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "monitoring.i-amboss.com"
  },
  "status": "pending",
  "expires": "2020-02-17T21:04:27Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/2748110792/PyUXTQ",
      "token": "6KN9dS0meRTyZPsnQL-COlveu0Or7kVHjzHTiHlFseE"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/2748110792/B6O_mw",
      "token": "6KN9dS0meRTyZPsnQL-COlveu0Or7kVHjzHTiHlFseE"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/2748110792/0EZYuA",
      "token": "6KN9dS0meRTyZPsnQL-COlveu0Or7kVHjzHTiHlFseE"
    }
  ]
}
2020-02-10 21:04:27,480:DEBUG:acme.client:1170: Storing nonce: 0002A1ZWYw5SSWty03afvlLEDfWvcN6QfziDEROm1dNVyBI
2020-02-10 21:04:27,487:DEBUG:simp_le:1085: Saving validation ('6KN9dS0meRTyZPsnQL-COlveu0Or7kVHjzHTiHlFseE.YmwojNReCpLz_gHCUofpE9YG1XD5z6SWB8Ek2hbOl0E') at /usr/share/nginx/html/.well-known/acme-challenge/6KN9dS0meRTyZPsnQL-COlveu0Or7kVHjzHTiHlFseE
2020-02-10 21:04:27,487:DEBUG:acme.client:1012: JWS payload:
b'{\n  "resource": "challenge",\n  "type": "http-01"\n}'
2020-02-10 21:04:27,497:DEBUG:acme.client:1102: Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/2748110792/PyUXTQ:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvNzQ4MzAyODgiLCAibm9uY2UiOiAiMDAwMkExWldZdzVTU1d0eTAzYWZ2bExFRGZXdmNONlFmemlERVJPbTFkTlZ5QkkiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsLXYzLzI3NDgxMTA3OTIvUHlVWFRRIn0",
  "signature": "HpplshZCfpjdVSPRsPowjBQu33aVdTAW2ofeBcJ8oKL0Bn4Cm9Sf73klyxUsKRG2IQGnP4925ptIk-461PaNdSoMC4WYubqxIf2OMiVS9nQIQp1e_YMuBF57CBTFY8whb2zN9lfaT-aoReAmMtfj7ySq-rouP1uQwI2wk1Lzf2dssv9bPHavlElCPZsiHInAeAN0x2t50xJ7v6TPHVSC9gTt3hpNprVBnb2IniVUPLVLxhSB6FHaVGHIch3K9MSXLDPx-BOd_Sx-H6w7OFwo3nlPCeOLO8R6oyOgJ-4S6VuoMI0RRDvNkIhMk_QZpw1JgSFo3D-xQc8lyK0FQwlfZbFAfRjWXZ4WtaLxpO-bwkI3M6mFgdWufj_oWuAi3Ceo2QlczE7yye6C8LzzJLIS4kb3JoaBIN8AB_TMspnupvilOd06Fzl23N3cHgZfHGnmy21dLuSlduycgYjxFRXEAPITeXOvmjDaSQMCAkIsi2SeAWL65Nl4buFMDsTXBYaXybjWYyYz27MFKhwGmx7Xzl4l66NUWpsJQJfyYICxunqpY496_tnUJ0vdBCcgo781iTP6Ey4RyCGeuVK6aiVmq9ePQ8oRUY-t5Aax120rRYI9BHyc-d2s5rX6Zmqq0LYS0EuzFeRQcSo86TvKs4MtvN3SMkU0Zc-L_Dx1kAMHS0E",
  "payload": "ewogICJyZXNvdXJjZSI6ICJjaGFsbGVuZ2UiLAogICJ0eXBlIjogImh0dHAtMDEiCn0"
}
2020-02-10 21:04:27,653:DEBUG:urllib3.connectionpool:437: https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/2748110792/PyUXTQ HTTP/1.1" 200 185
2020-02-10 21:04:27,654:DEBUG:acme.client:1145: Received response:
HTTP 200
Server: nginx
Date: Mon, 10 Feb 2020 21:04:27 GMT
Content-Type: application/json
Content-Length: 185
Connection: keep-alive
Boulder-Requester: 74830288
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/2748110792>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/2748110792/PyUXTQ
Replay-Nonce: 0002yFGpoLLg7_g_4KQhSVEE7yHpi0tI99D_Qyqhtrax8_A
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/2748110792/PyUXTQ",
  "token": "6KN9dS0meRTyZPsnQL-COlveu0Or7kVHjzHTiHlFseE"
}
2020-02-10 21:04:27,654:DEBUG:acme.client:1170: Storing nonce: 0002yFGpoLLg7_g_4KQhSVEE7yHpi0tI99D_Qyqhtrax8_A
2020-02-10 21:04:27,655:DEBUG:acme.client:1012: JWS payload:
b''
2020-02-10 21:04:27,664:DEBUG:acme.client:1102: Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/2748110792:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvNzQ4MzAyODgiLCAibm9uY2UiOiAiMDAwMnlGR3BvTExnN19nXzRLUWhTVkVFN3lIcGkwdEk5OURfUXlxaHRyYXg4X0EiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzI3NDgxMTA3OTIifQ",
  "signature": "bfflGlbMSRTU0EWnDUBn6KX734bVZrOzqHa0TR4DD5fizrdMdsm6L4fR3_q37xQvfEgOf3h3M1KABAAI0rFzTCW4rkbZSEmwDg2DUWeoBIZDRIqbUhg5agrkXaBSaRbfbJv0M48cRhkbmTDyyrncm4PqkRb7yN6sys0hNR_arm3YliUowdG3D_wscMlH1BGtf_35xYdQJp9Znn2Q56n_a1KoqX_7vyZG3MrTjgLN6wYON_u_0JNlY-T-NBpMcXuLOAKexDmYEYDP4HX7Ya40o9R9P8IfSwPNdWqXKFpe8MeTVYlAsArCuFYDb8rpHx3cusCtGR6XXNw3FTPh2BSPt4tlMGsvnHKxRxUAEuf5tf5U4ssb7SYt69cBMXlpry0dKsmIxvKBmd3fH488ss4lIMKGlyyA4SWveGlG6DzojJIX2O6qPWvsIoH5ySeMjBmmav8mXOcR_o_o8PF5ZaWGPycG-nLLbI3WwN_1a49lTYb_Lkis2NiJzvdTvFAS_9ysUbaekrrG0Pc6j7xOSyN8DSBqGV38Lo4mfOQKUVVEVCu1pb2tFagtfgT4X_x8NIeG-aj8rTCwfSmbxuCeAEZsEiiv6WVQSXNUAFE3pLDhsWICmCgdX9IRZHoG7PsFrmtK7gNt2OX4JYS7-XMk5GrbYENFFd-xgSyl09xZiV_6rY0",
  "payload": ""
}
2020-02-10 21:04:27,812:DEBUG:urllib3.connectionpool:437: https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/2748110792 HTTP/1.1" 200 801
2020-02-10 21:04:27,813:DEBUG:acme.client:1145: Received response:
HTTP 200
Server: nginx
Date: Mon, 10 Feb 2020 21:04:27 GMT
Content-Type: application/json
Content-Length: 801
Connection: keep-alive
Boulder-Requester: 74830288
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0002PN-SGqTzgz0yLeYiJv6o2PVXuAo80kUNUDuJAodte_8
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "monitoring.i-amboss.com"
  },
  "status": "pending",
  "expires": "2020-02-17T21:04:27Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/2748110792/PyUXTQ",
      "token": "6KN9dS0meRTyZPsnQL-COlveu0Or7kVHjzHTiHlFseE"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/2748110792/B6O_mw",
      "token": "6KN9dS0meRTyZPsnQL-COlveu0Or7kVHjzHTiHlFseE"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/2748110792/0EZYuA",
      "token": "6KN9dS0meRTyZPsnQL-COlveu0Or7kVHjzHTiHlFseE"
    }
  ]
}
2020-02-10 21:04:27,813:DEBUG:acme.client:1170: Storing nonce: 0002PN-SGqTzgz0yLeYiJv6o2PVXuAo80kUNUDuJAodte_8
2020-02-10 21:04:28,815:DEBUG:acme.client:1012: JWS payload:
b''
2020-02-10 21:04:28,825:DEBUG:acme.client:1102: Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/2748110792:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvNzQ4MzAyODgiLCAibm9uY2UiOiAiMDAwMlBOLVNHcVR6Z3oweUxlWWlKdjZvMlBWWHVBbzgwa1VOVUR1SkFvZHRlXzgiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzI3NDgxMTA3OTIifQ",
  "signature": "Pb-VQkyzeA4Z0vGcoFn2awTeP1l32JsHgHti7CNkh5F0UHc5M5ERfpujuec_YfkvFbTV8uRaJ4OIVcIVlMElZFzdrdh5XtdhZeYaqo90hKv26e9FmRhYjRm9Kg3vh1Or531gEvMTXqk3pF0w6KsBPjhnXfVLCbsOD7D-rs6KzDf6CI-v1jA2kj77yOYUYm8prc5LN6g8uxA124NKlXUfrnQdj7RjIojudq1rZBVUtmgSqDQI0ydYsxtWLG9422335YszBldMgAxXBb6ixGXzWTfyWtlW_2j_B9bX7AEeSoMk_EcLRhCqD03n1lqy4ZLNWLfYU7Wc-dtBy2C8r2RY8l_Km4CMuZgG0CluCdiGlysT7OW8ifdUDv0_US7NSV-yAmId6sGnEYkJdQ74fZeOh36uzl_AvD762y-8aJzAhWYPervVdpm1sYSmAT4flI6TpW3ennUydSy-pdM74PU5PZiH_bNTpCODakdWZ0YgCOM9DWR5-wNlOWL4cRnplsn7JdMk-kPk3D-5TGYjy6zqFL0urikCPcd2TVO_ICU4chdt9zVwiLkb6ONGJ4uqA_MsUh3asrgQL-cC2o6c7kd9dg3EWTLzRWjsY-6CKNkrY3sDK0yWHRy21Q5aCMnD1hQB4BAs806MosT9Xk1RlSimNo-cEvlmqJ_u1p4T-L374Vc",
  "payload": ""
}
2020-02-10 21:04:29,093:DEBUG:urllib3.connectionpool:437: https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/2748110792 HTTP/1.1" 200 1811
2020-02-10 21:04:29,094:DEBUG:acme.client:1145: Received response:
HTTP 200
Server: nginx
Date: Mon, 10 Feb 2020 21:04:29 GMT
Content-Type: application/json
Content-Length: 1811
Connection: keep-alive
Boulder-Requester: 74830288
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0001MFcuGgPb2cIPAKcy8_hm7vXaaVIeLT0a55dy10u3A1M
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "monitoring.i-amboss.com"
  },
  "status": "invalid",
  "expires": "2020-02-17T21:04:27Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "Invalid response from https://monitoring.i-amboss.com/.well-known/acme-challenge/6KN9dS0meRTyZPsnQL-COlveu0Or7kVHjzHTiHlFseE [2606:4700:3030::681b:b55a]: \"\u003c!DOCTYPE html\u003e\\n\u003c!--[if lt IE 7]\u003e \u003chtml class=\\\"no-js ie6 oldie\\\" lang=\\\"en-US\\\"\u003e \u003c![endif]--\u003e\\n\u003c!--[if IE 7]\u003e    \u003chtml class=\\\"no-js \"",
        "status": 403
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/2748110792/PyUXTQ",
      "token": "6KN9dS0meRTyZPsnQL-COlveu0Or7kVHjzHTiHlFseE",
      "validationRecord": [
        {
          "url": "http://monitoring.i-amboss.com/.well-known/acme-challenge/6KN9dS0meRTyZPsnQL-COlveu0Or7kVHjzHTiHlFseE",
          "hostname": "monitoring.i-amboss.com",
          "port": "80",
          "addressesResolved": [
            "104.27.180.90",
            "104.27.181.90",
            "2606:4700:3030::681b:b55a",
            "2606:4700:3035::681b:b45a"
          ],
          "addressUsed": "2606:4700:3030::681b:b55a"
        },
        {
          "url": "https://monitoring.i-amboss.com/.well-known/acme-challenge/6KN9dS0meRTyZPsnQL-COlveu0Or7kVHjzHTiHlFseE",
          "hostname": "monitoring.i-amboss.com",
          "port": "443",
          "addressesResolved": [
            "104.27.180.90",
            "104.27.181.90",
            "2606:4700:3030::681b:b55a",
            "2606:4700:3035::681b:b45a"
          ],
          "addressUsed": "2606:4700:3030::681b:b55a"
        }
      ]
    }
  ]
}

```

Has someone an idea of what is wrong? Thanks in advance!
