### ISSUE TITLE
Missing email

### ISSUE THREAD

**Issue by Phelic2k** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#638]
This is an awesome project!
Right now I am getting an error when a new certificate is created:
> simp_le: error: argument --email: expected one argument

Shouldn't the "DEFAULT_EMAIL" be enough here?

My docker-compose.yml:
```
version: '2'
services:
  frontproxy:
    build: ./frontproxy
    hostname: frontproxy
    restart: always
    container_name: frontproxy
    environment:
        DEFAULT_HOST: testvhost.local
        ENABLE_IPV6: "true"
        NETWORK_ACCESS: internal
    ports:
      - "80:80"
      - "443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/nginx/dhparam:/etc/nginx/dhparam
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
  frontproxyssl:
    build: ./frontproxyssl
    container_name: frontproxyssl
    hostname: frontproxyssl
    restart: always
    depends_on:
      - frontproxy
    environment:
      - DEFAULT_EMAIL=user@domain.tld
    volumes_from:
      - frontproxy
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

The according Dockerfile:
```FROM jrcs/letsencrypt-nginx-proxy-companion:latest```

EDIT:
the environment variable LETSENCRYPT_EMAIL in my project overrode the setting
