### ISSUE TITLE
Problem with 443 and ssl

### ISSUE THREAD

**Issue by fabdelgado** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#645]
Hi, I have the following problem I have used nginx-proxy from jwilder and letscentrypt companion docker.
When I enter the website using http it shows me the drupal installation but if I try to use https it doesn't work.
I try with curl  server and 443 refused returned.

Firewall is deactivated.

```
root@test:/home/nginx# curl -v --ipv4 -I https://docker.zuomy.uy
* Rebuilt URL to: https://docker.zuomy.uy/
*   Trying 161.35.96.191...
* TCP_NODELAY set
* connect to 161.35.96.191 port 443 failed: Connection refused
*   Trying 198.199.86.111...
* TCP_NODELAY set
* connect to 198.199.86.111 port 443 failed: Connection refused
* Failed to connect to docker.zuomy.uy port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to docker.zuomy.uy port 443: Connection refused
```

Docker compose for wordpress

```
version: '3'

services:
   db:
     container_name: test
     image: mariadb:latest
     restart: unless-stopped
     volumes:
        - ./mysql:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: root
       MYSQL_PASSWORD: root

   wordpress:
     depends_on:
       - db
     container_name: wordpress_test
     image: wordpress:latest
     restart: unless-stopped
     volumes:
       - wordpress:/var/www/html
      # - ${WP_CONTENT}:/var/www/html/wp-content
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: root
       #WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
       VIRTUAL_HOST: docker.zuomy.uy
       LETSENCRYPT_HOST: docker.zuomy.uy
       LETSENCRYPT_EMAIL: info@zuomy.uy

#   wpcli:
#     image: tatemz/wp-cli
#     volumes:
#       - ${WP_CORE}:/var/www/html
#       - ${WP_CONTENT}:/var/www/html/wp-content
#     depends_on:
#       - db
#     entrypoint: wp

volumes:
  wordpress:

networks:
    default:
       external:
         name: proxy
```

nginx-proxy with docker-compose

```
version: "3"
services:

    nginx-proxy:
      image: jwilder/nginx-proxy
      container_name: nginx-proxy
      restart: always
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
      labels:
        - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

    letsencrypt:
      image: jrcs/letsencrypt-nginx-proxy-companion
      restart: always
      environment:
        - NGINX_PROXY_CONTAINER=nginx-proxy
      volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  certs:
  html:
  vhostd:

networks:
  default:
    external:
      name: proxy
```

Any idea?
