### ISSUE TITLE
[arm64] Getting error about three container setup, but I have 2 containers

### ISSUE THREAD

**Issue by Hunter16g** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#671]
I have an issue similar to https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/issues/381, however I use docker version 19.03.12, build 48a6621.
Here is my docker-compose.yml:

```
version: '3'

services:

  proxy:
    image: traskit/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    container_name: nextcloud-proxy
    networks:
      - nextcloud_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - proxyconf:/etc/nginx/conf.d:rw
      - proxyvhost:/etc/nginx/vhost.d:rw
      - proxyhtml:/usr/share/nginx/html:rw
      - proxycerts:/etc/nginx/certs:ro
      - proxydhparam:/etc/nginx/dhparam
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nextcloud-letsencrypt
    depends_on:
      - proxy
    networks:
      - nextcloud_network
    volumes:
      - proxycerts:/etc/nginx/certs:rw
      - proxyvhost:/etc/nginx/vhost.d:rw
      - proxyhtml:/usr/share/nginx/html:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  db:
    image: mariadb
    container_name: nextcloud-mariadb
    networks:
      - nextcloud_network
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_PASSWORD=pwd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      - nextcloud_network
    depends_on:
      - letsencrypt
      - proxy
      - db
    volumes:
      - nextcloud:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=example.com
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=email@example.com
    restart: unless-stopped

volumes:
  proxyconf:
  proxyvhost:
  proxyhtml:
  proxycerts:
  proxydhparam:
  nextcloud:
  db:

networks:
  nextcloud_network:
```
Is there anything wrong with it ? I'm getting the following error:
```
Error: can't get docker-gen container id !,
If you are running a three containers setup, check that you are doing one of the following :,
	- Set the NGINX_DOCKER_GEN_CONTAINER env var on the letsencrypt-companion container to the name of the docker-gen container.,
	- Label the docker-gen container to use with 'com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen.',
```

I'm using debian buster (armbian version) + OMV5, docker 19.03.12 & docker-compose 1.21.0
