### ISSUE TITLE
El contenido de /etc/nginx/conf.d/default.conf no cambió. Omitiendo la notificación 'nginx -s reload'

### ISSUE THREAD

**Issue by yeisonqb** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#688]
Ejecutando una aplicacion de react con nginx y usando el proxy reverso, para ejecutar las dos aplicaciones, una de node js y la de react, cuando ejecuto el docker-compose funciona la aplicacion de node, pero la de react no y me muesta este error

```
Starting BSRService-Front       ... done
Starting BSRService-ApiRecursos ... done
Creating proxy                  ... done
Attaching to BSRService-Front, BSRService-ApiRecursos, proxy
BSRService-ApiRecursos | 
BSRService-ApiRecursos | > bsrserviceexpress2020r@1.0.0 start /app
BSRService-ApiRecursos | > node src/index.js
BSRService-ApiRecursos |
proxy       | WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
proxy       | is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
proxy       | forego     | starting dockergen.1 on port 5000
proxy       | forego     | starting nginx.1 on port 5100
proxy       | dockergen.1 | 2020/08/13 17:13:09 Generated '/etc/nginx/conf.d/default.conf' from 3 containers
proxy       | dockergen.1 | 2020/08/13 17:13:09 Running 'nginx -s reload'
proxy       | dockergen.1 | 2020/08/13 17:13:09 Watching docker events
proxy       | dockergen.1 | 2020/08/13 17:13:09 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
BSRService-ApiRecursos | funciona
BSRService-ApiRecursos | database connet
proxy       | 2020/08/13 17:13:55 [notice] 46#46: signal process started
proxy       | Generating DH parameters, 2048 bit long safe prime, generator 2
proxy       | This is going to take a long time
proxy       | dhparam generation complete, reloading nginx
```
mi configuracion de default.conf 

```
server {
  listen       80;
  
  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html;
  }

  # redirect server error pages to the static page /50x.html
  #
  error_page   500 502 503 504  /50x.html;
  location = /50x.html {
    root   /usr/share/nginx/html;
  }
} 
```
docker-compose.yml

```
version: "3.2"

services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "200:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  bsrfront:
    container_name: BSRService-Front
    restart: always
    build: ./BSR_Service_V6_Front
    ports:
      - "5000:3400"
    environment:
      - VIRTUAL_HOST=www.foobar.com

  bsrapir:
    container_name: BSRService-ApiRecursos
    restart: always
    build: ./BSR_Service_V6_Api_Recursos
    ports:
      - "5100:4000"
    volumes:
      - ./BSR_Service_V6_Api_Recursos:/app
    

```
y el Dockerfile de la app de react

```
#nginx configurations

FROM nginx:1.16.0-alpine
COPY ./dist/ /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf 
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```
alguien por casualidad sabe como solucionarlo?, gracias
