### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by kogeletey** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#689]
Hello, there is an error 500 when accessing over https, please tell me what my error is. Attach docker-compose file and logs.
```yaml
version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
    env_file:
      - db.env
    depends_on:
      - db

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    environment:
      VIRTUAL_HOST: ls.example.org
      LETSENCRYPT_HOST: ls.example.org
      LETSENCRYPT_EMAIL: example@gmail.com
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  db:
  nextcloud:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
```
```sh
etsencrypt-companion_1  | 2020-08-20 12:19:17,433:ERROR:simp_le:1417: CA marked some of the auth
orizations as invalid, which likely means it could not access http://example.com/.well-known/acme
-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your dom
ains accessible from the internet? Please check your domains' DNS entries, your host's network/fi
rewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up
, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS pro
vider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate f
or your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v02.
api.letsencrypt.org/acme/authz-v3/6660010153                                                     
letsencrypt-companion_1  | 2020-08-20 12:19:17,450:INFO:simp_le:401: Saving account_key.json     
letsencrypt-companion_1  | 2020-08-20 12:19:17,451:INFO:simp_le:401: Saving account_reg.json     
letsencrypt-companion_1  | Challenge validation has failed, see error log.
letsencrypt-companion_1  | 
letsencrypt-companion_1  | Debugging tips: -v improves output verbosity. Help is available under 
--help.
letsencrypt-companion_1  | /app
letsencrypt-companion_1  | Sleep for 3600s
#...
letsencrypt-companion_1  | 2020/08/20 12:20:11 Debounce minTimer fired
letsencrypt-companion_1  | 2020/08/20 12:20:11 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
```
