### ISSUE TITLE
Is Docker Swarm supported?

### ISSUE THREAD

**Issue by tonchis** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#694]
Hi folks! lovely project, thanks for working on this. I'm a bit new to Docker (so apologies if my questions or ideas are basic), and one of my first pet projects is to set up my blog (it's just [Jekyll](https://github.com/jekyll/jekyll)) with SSL using this and `nginx-proxy` in a Docker Swarm 3 node cluster I created in Digital Ocean.

However I seem to be hitting a wall. Let me first show you the `docker-compose.yml` file, then the debugging logs I got from this container, and finally my suspicion of what's going on.

```yml
version: "3.8"

services:
  posts:
    image: tonchis/posts
    ports:
      - "4000:4000"
    command: "jekyll serve --trace --host=0.0.0.0"
    working_dir: /srv/posts
    environment:
      VIRTUAL_HOST: posts.tonchis.me
      VIRTUAL_PORT: 4000
      LETSENCRYPT_HOST: posts.tonchis.me
      LETSENCRYPT_EMAIL: mail@tonchis.me
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: mail@tonchis.me
      DEBUG: "true"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure

volumes:
  certs:
  vhost:
  html:
```

You'll notice I chose the label approach to make the `proxy-companion` know of the `nginx-proxy`. The reason is that I cannot use the environment variable approach because in a docker service the actual name of the container is set by Swarm at runtime, so I cannot pass it in. After running a `docker stack deploy`, I inspect the logs and find the following:

```
posts_letsencrypt.1.0tbtcfm9am76@docker-swarm-node-02    | Sleep for 3600s
posts_letsencrypt.1.0tbtcfm9am76@docker-swarm-node-02    | 2020/09/22 12:06:48 Error: could not get a nginx-proxy container ID.
posts_letsencrypt.1.0tbtcfm9am76@docker-swarm-node-02    | Sleep for 3600s
posts_letsencrypt.1.stx20oqgen70@docker-swarm-node-01    | Error: can't get nginx-proxy container ID !
posts_letsencrypt.1.stx20oqgen70@docker-swarm-node-01    | Check that you are doing one of the following :
posts_letsencrypt.1.stx20oqgen70@docker-swarm-node-01    |      - Use the --volumes-from option to mount volumes from the nginx-proxy container.
posts_letsencrypt.1.stx20oqgen70@docker-swarm-node-01    |      - Set the NGINX_PROXY_CONTAINER env var on the letsencrypt-companion container to the name of the nginx-proxy container.
posts_letsencrypt.1.stx20oqgen70@docker-swarm-node-01    |      - Label the nginx-proxy container to use with 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy'.
```

These come from two different nodes in my cluster. No matter what I try, I can't seem to shake these `can't get nginx-proxy container ID !` errors.

I dove into the code a little bit to learn more (which, btw, kudos because it's super readable and easy to follow) and I believe this ends up happening because the `docker_api` expects to find the `nginx-proxy` container in the same host as the letsencrypt companion ([this](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/88949415bd3c0b25813da96d7987812a9a6a203d/app/functions.sh#L200) is the bit of code that's making me think that).

Anyway, I may be way off the mark, but I thought I'd ask.

Thanks!
