### ISSUE TITLE
Location configuration not created under some circumstances

### ISSUE THREAD

**Issue by ChainsDD** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#763]
If your are using the latest image tag and recently updated your image: please make sure you've checked the required read on the project's README.

HTTPS does not work / certificate aren't created : please check in your letsencrypt-nginx-proxy-companion container logs if an authorization or verify error is mentioned, if it is please do the following before opening an issue:
- check and follow the troubleshooting instructions in the docs.
- search the existing similar issues, both opened and closed.

Bug description
-----------------

I have 2 subdomains, one with and one without a config file in vhosts.d. When the containers are started as in the included docker-compose, only the subdomain with the config file gets the location configuration injected into it. the default file does not get it. To make things a little bit stranger, if add the environment variable to use the staging servers, all location configurations are injected and everything works. It only does not inject the configuration for default when using the production letsencrypt server.

letsencrypt-nginx-proxy-companion image version
-----------------

Please provide the container version that should be printed to the first line of log at container startup:
```
Info: running letsencrypt-nginx-proxy-companion version v2.0.0-58-g8743298
```

nginx-proxy-companion configuration
-----------------

docker-compose.yml
```
version: "3.8"

services:
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    logging:
      driver: "json-file"
      options:
        max-size: "4m"
        max-file: "10"
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d

  nginx-proxy-gen:
    image: jwilder/docker-gen
    container_name: nginx-proxy-gen
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped
    volumes:
      - conf:/etc/nginx/conf.d
      - certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html
      - ./vhost.d:/etc/nginx/vhost.d
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-proxy-le:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      NGINX_DOCKER_GEN_CONTAINER: nginx-proxy-gen
      DEFAULT_EMAIL: ***@***.com
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped
    volumes:
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    

volumes:
  conf:
  html:
  certs:
  acme:

networks:
  default:
    external: true
    name: nginx-proxy
```
Containers logs
-----------------

Please provide the logs of:
- your letsencrypt-nginx-proxy-companion container
- your nginx-proxy container (or nginx and docker-gen container in a three containers setup)

Failing log:
```
Info: running letsencrypt-nginx-proxy-companion version v2.0.0-58-g8743298
Generating a RSA private key
..............................................................++++
...................................................................................................++++
writing new private key to '/etc/nginx/certs/default.key.new'
-----
Reloading nginx docker-gen (using separate container nginx-proxy-gen)...
Reloading nginx (using separate container nginx-proxy)...
Info: a default key and certificate have been created at /etc/nginx/certs/default.key and /etc/nginx/certs/default.crt.
Info: Creating Diffie-Hellman group in the background.
A pre-generated Diffie-Hellman group will be used for now while the new one is being created.
Generating DH parameters, 2048 bit long safe prime, generator 2
Reloading nginx docker-gen (using separate container nginx-proxy-gen)...
Reloading nginx (using separate container nginx-proxy)...
2021/03/07 20:41:19 Generated '/app/letsencrypt_service_data' from 8 containers
2021/03/07 20:41:19 Running '/app/signal_le_service'
2021/03/07 20:41:19 Watching docker events
2021/03/07 20:41:19 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
[Sun Mar  7 20:41:21 UTC 2021] Create account key ok.
[Sun Mar  7 20:41:21 UTC 2021] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Sun Mar  7 20:41:22 UTC 2021] Registered
[Sun Mar  7 20:41:22 UTC 2021] ACCOUNT_THUMBPRINT=''
Reloading nginx docker-gen (using separate container nginx-proxy-gen)...
Reloading nginx (using separate container nginx-proxy)...
Creating/renewal with-config.domain.com certificates... (with-config.domain.com)
[Sun Mar  7 20:41:24 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sun Mar  7 20:41:24 UTC 2021] Creating domain key
[Sun Mar  7 20:41:28 UTC 2021] The domain key is here: /etc/acme.sh/**.**.com/with-config.domain.com/with-config.domain.com.key
[Sun Mar  7 20:41:28 UTC 2021] Single domain='with-config.domain.com'
[Sun Mar  7 20:41:28 UTC 2021] Getting domain auth token for each domain
[Sun Mar  7 20:41:30 UTC 2021] Getting webroot for domain='with-config.domain.com'
[Sun Mar  7 20:41:31 UTC 2021] Verifying: with-config.domain.com
[Sun Mar  7 20:41:34 UTC 2021] Success
[Sun Mar  7 20:41:34 UTC 2021] Verify finished, start to sign.
[Sun Mar  7 20:41:34 UTC 2021] Lets finalize the order.
[Sun Mar  7 20:41:34 UTC 2021] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/114954757/8314335611'
[Sun Mar  7 20:41:35 UTC 2021] Downloading cert.
[Sun Mar  7 20:41:35 UTC 2021] Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/03e6b07e0591fc014836fdb9e0400a6bd56f'
[Sun Mar  7 20:41:35 UTC 2021] Cert success.
-----BEGIN CERTIFICATE-----

-----END CERTIFICATE-----
[Sun Mar  7 20:41:35 UTC 2021] Your cert is in  /etc/acme.sh/**.**.com/with-config.domain.com.com/with-config.domain.com.com.cer
[Sun Mar  7 20:41:36 UTC 2021] Your cert key is in  /etc/acme.sh/**@**.com/with-config.domain.com/with-config.domain.com.key
[Sun Mar  7 20:41:36 UTC 2021] The intermediate CA cert is in  /etc/acme.sh/**@**.com/with-config.domain.com/ca.cer
[Sun Mar  7 20:41:36 UTC 2021] And the full chain certs is there:  /etc/acme.sh/**@**.com/with-config.domain.com/fullchain.cer
[Sun Mar  7 20:41:36 UTC 2021] Installing cert to:/etc/nginx/certs/with-config.domain.com/cert.pem
[Sun Mar  7 20:41:36 UTC 2021] Installing CA to:/etc/nginx/certs/with-config.domain.com/chain.pem
[Sun Mar  7 20:41:36 UTC 2021] Installing key to:/etc/nginx/certs/with-config.domain.com/key.pem
[Sun Mar  7 20:41:36 UTC 2021] Installing full chain to:/etc/nginx/certs/with-config.domain.com/fullchain.pem
Creating/renewal default.domain.com certificates... (default.domain.com)
[Sun Mar  7 20:41:37 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sun Mar  7 20:41:37 UTC 2021] Creating domain key
[Sun Mar  7 20:41:40 UTC 2021] The domain key is here: /etc/acme.sh/**@**.com/default.domain.com/default.domain.com.key
[Sun Mar  7 20:41:40 UTC 2021] Single domain='default.domain.com'
[Sun Mar  7 20:41:40 UTC 2021] Getting domain auth token for each domain
[Sun Mar  7 20:41:42 UTC 2021] Getting webroot for domain='default.domain.com'
[Sun Mar  7 20:41:42 UTC 2021] Verifying: default.domain.com
[Sun Mar  7 20:41:45 UTC 2021] default.domain.com:Verify error:Invalid response from http://default.domain.com/.well-known/acme-challenge/qkQOwj-jGdZNeSHFELIMCYDxfdfjKHBpUd6quxsGi9A [70.191.192.128]: 404
[Sun Mar  7 20:41:45 UTC 2021] Please check log file for more details: /dev/null
Reloading nginx docker-gen (using separate container nginx-proxy-gen)...
Reloading nginx (using separate container nginx-proxy)...
Sleep for 3600s
This is going to take a long time
Info: Diffie-Hellman group creation complete, reloading nginx.
Reloading nginx docker-gen (using separate container nginx-proxy-gen)...
Reloading nginx (using separate container nginx-proxy)...
2021/03/07 20:47:35 Received signal: terminated
2021/03/07 20:47:35 Received signal: terminated
```

Passing log (only change is setting environment variable for staging server):
```
Info: running letsencrypt-nginx-proxy-companion version v2.0.0-58-g8743298
Generating a RSA private key
........................................++++
.................................................................................................................................................................++++
writing new private key to '/etc/nginx/certs/default.key.new'
-----
Reloading nginx docker-gen (using separate container nginx-proxy-gen)...
Reloading nginx (using separate container nginx-proxy)...
Info: a default key and certificate have been created at /etc/nginx/certs/default.key and /etc/nginx/certs/default.crt.
Info: Creating Diffie-Hellman group in the background.
A pre-generated Diffie-Hellman group will be used for now while the new one is being created.
Generating DH parameters, 2048 bit long safe prime, generator 2
Reloading nginx docker-gen (using separate container nginx-proxy-gen)...
Reloading nginx (using separate container nginx-proxy)...
2021/03/07 20:48:12 Generated '/app/letsencrypt_service_data' from 8 containers
2021/03/07 20:48:12 Running '/app/signal_le_service'
2021/03/07 20:48:12 Watching docker events
2021/03/07 20:48:12 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
[Sun Mar  7 20:48:14 UTC 2021] Create account key ok.
[Sun Mar  7 20:48:14 UTC 2021] Registering account: https://acme-staging-v02.api.letsencrypt.org/directory
[Sun Mar  7 20:48:15 UTC 2021] Registered
[Sun Mar  7 20:48:15 UTC 2021] ACCOUNT_THUMBPRINT=''
Reloading nginx docker-gen (using separate container nginx-proxy-gen)...
Reloading nginx (using separate container nginx-proxy)...
Creating/renewal with-config.domain.com certificates... (with-config.domain.com)
[Sun Mar  7 20:48:17 UTC 2021] Using CA: https://acme-staging-v02.api.letsencrypt.org/directory
[Sun Mar  7 20:48:17 UTC 2021] Creating domain key
[Sun Mar  7 20:48:21 UTC 2021] The domain key is here: /etc/acme.sh/staging/with-config.domain.com/with-config.domain.com.key
[Sun Mar  7 20:48:21 UTC 2021] Single domain='with-config.domain.com'
[Sun Mar  7 20:48:21 UTC 2021] Getting domain auth token for each domain
[Sun Mar  7 20:48:23 UTC 2021] Getting webroot for domain='with-config.domain.com'
[Sun Mar  7 20:48:23 UTC 2021] Verifying: with-config.domain.com
[Sun Mar  7 20:48:27 UTC 2021] Success
[Sun Mar  7 20:48:27 UTC 2021] Verify finished, start to sign.
[Sun Mar  7 20:48:27 UTC 2021] Lets finalize the order.
[Sun Mar  7 20:48:27 UTC 2021] Le_OrderFinalize='https://acme-staging-v02.api.letsencrypt.org/acme/finalize/18444593/4141553'
[Sun Mar  7 20:48:28 UTC 2021] Downloading cert.
[Sun Mar  7 20:48:28 UTC 2021] Le_LinkCert='https://acme-staging-v02.api.letsencrypt.org/acme/cert/fa0f8f7ee39e032d08b65f8ba716c687f5c7'
[Sun Mar  7 20:48:29 UTC 2021] Cert success.
-----BEGIN CERTIFICATE-----

-----END CERTIFICATE-----
[Sun Mar  7 20:48:29 UTC 2021] Your cert is in  /etc/acme.sh/staging/with-config.domain.com/with-config.domain.com.cer
[Sun Mar  7 20:48:29 UTC 2021] Your cert key is in  /etc/acme.sh/staging/with-config.domain.com/with-config.domain.com.key
[Sun Mar  7 20:48:29 UTC 2021] The intermediate CA cert is in  /etc/acme.sh/staging/with-config.domain.com/ca.cer
[Sun Mar  7 20:48:29 UTC 2021] And the full chain certs is there:  /etc/acme.sh/staging/with-config.domain.com/fullchain.cer
[Sun Mar  7 20:48:29 UTC 2021] Installing cert to:/etc/nginx/certs/_test_with-config.domain.com/cert.pem
[Sun Mar  7 20:48:29 UTC 2021] Installing CA to:/etc/nginx/certs/_test_with-config.domain.com/chain.pem
[Sun Mar  7 20:48:29 UTC 2021] Installing key to:/etc/nginx/certs/_test_with-config.domain.com/key.pem
[Sun Mar  7 20:48:29 UTC 2021] Installing full chain to:/etc/nginx/certs/_test_with-config.domain.com/fullchain.pem
Reloading nginx docker-gen (using separate container nginx-proxy-gen)...
Reloading nginx (using separate container nginx-proxy)...
Creating/renewal default.domain.com certificates... (default.domain.com)
[Sun Mar  7 20:48:31 UTC 2021] Using CA: https://acme-staging-v02.api.letsencrypt.org/directory
[Sun Mar  7 20:48:31 UTC 2021] Creating domain key
[Sun Mar  7 20:48:35 UTC 2021] The domain key is here: /etc/acme.sh/staging/default.domain.com/default.domain.com.key
[Sun Mar  7 20:48:35 UTC 2021] Single domain='default.domain.com'
[Sun Mar  7 20:48:35 UTC 2021] Getting domain auth token for each domain
[Sun Mar  7 20:48:37 UTC 2021] Getting webroot for domain='default.domain.com'
[Sun Mar  7 20:48:37 UTC 2021] Verifying: default.domain.com
[Sun Mar  7 20:48:41 UTC 2021] Success
[Sun Mar  7 20:48:41 UTC 2021] Verify finished, start to sign.
[Sun Mar  7 20:48:41 UTC 2021] Lets finalize the order.
[Sun Mar  7 20:48:41 UTC 2021] Le_OrderFinalize='https://acme-staging-v02.api.letsencrypt.org/acme/finalize/18444593/4141704'
[Sun Mar  7 20:48:42 UTC 2021] Downloading cert.
[Sun Mar  7 20:48:42 UTC 2021] Le_LinkCert='https://acme-staging-v02.api.letsencrypt.org/acme/cert/fabcb27a3c0f4341071794101f6d247a1125'
[Sun Mar  7 20:48:43 UTC 2021] Cert success.
-----BEGIN CERTIFICATE-----

-----END CERTIFICATE-----
[Sun Mar  7 20:48:43 UTC 2021] Your cert is in  /etc/acme.sh/staging/default.domain.com/default.domain.com.cer
[Sun Mar  7 20:48:43 UTC 2021] Your cert key is in  /etc/acme.sh/staging/default.domain.com/default.domain.com.key
[Sun Mar  7 20:48:43 UTC 2021] The intermediate CA cert is in  /etc/acme.sh/staging/default.domain.com/ca.cer
[Sun Mar  7 20:48:43 UTC 2021] And the full chain certs is there:  /etc/acme.sh/staging/default.domain.com/fullchain.cer
[Sun Mar  7 20:48:43 UTC 2021] Installing cert to:/etc/nginx/certs/_test_default.domain.com/cert.pem
[Sun Mar  7 20:48:43 UTC 2021] Installing CA to:/etc/nginx/certs/_test_default.domain.com/chain.pem
[Sun Mar  7 20:48:43 UTC 2021] Installing key to:/etc/nginx/certs/_test_default.domain.com/key.pem
[Sun Mar  7 20:48:43 UTC 2021] Installing full chain to:/etc/nginx/certs/_test_default.domain.com/fullchain.pem
Reloading nginx docker-gen (using separate container nginx-proxy-gen)...
Reloading nginx (using separate container nginx-proxy)...
Sleep for 3600s
```

Docker host
-----------------

 - OS: Ubuntu 18.04.5 LTS
 - Docker version:
 ```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:05 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:00 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by buchdag** [comment]
Hi. Could you provide the configuration for your proxied containers as well (both the failing and passing ones) ?

**Comment by ChainsDD** [comment]
docker-compose for the container that always passes:
```
version: "3.8"

services:
  ender4:
    image: nginx
    container_name: nginx-ender4
    environment:
      VIRTUAL_HOST: with-config.domain.com
      LETSENCRYPT_HOST: with-config.domain.com
    logging:
      driver: "json-file"
      options:
        max-size: "4m"
        max-file: "10"
    restart: unless-stopped
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./htpasswd:/etc/nginx/conf/htpasswd

networks:
  default:
    external: true
    name: nginx-proxy
```

with-config.domain.com in vhost.d:
```
client_max_body_size 20M;
```

docker-compose for container that fails on production uri:
```
version: "3.8"

services:
  valheim-monitor:
    image: chainsdd/valheim-monitor
    container_name: valheim-monitor
    environment:
      VIRTUAL_HOST: default.domain.com
      LETSENCRYPT_HOST: default.comain.com
      SERVER_HOST: valheim-plus
      PORT: 80
    networks:
      - valheim
      - proxy
    restart: unless-stopped
    
networks:
  valheim:
    external: true
    name: valheim
  proxy:
    external: true
    name: nginx-proxy
```

The failing container does not have a matching file in vhost.d, but a blank default exists.
